### ISSUE TITLE
Unecessary typescript dependency

### ISSUE THREAD

**Issue by nbonfils** [kwameopareasiedu/vanjs-routing#3]
I think `typescript` could be a `devDependency`.
This way someone adding `vanjs-routing` to a project that doesn't use typescript, doesn't need to pull in `typescript` with it.

https://github.com/kwameopareasiedu/vanjs-routing/blob/2f66e5424c763fd6935316a72f6b3ba80cbc5fb9/package.json#L29-L31

**Comment by kwameopareasiedu** [comment]
@nbonfils This is resolved in v1.1.4 ...
